version: "3.9"

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: "192.168.178.0/24"
          ip_range: "192.168.178.19/32"
          gateway: "192.168.178.1"

services:
  caddy:
    container_name: caddy
    image: caddy:2.5.2-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${PWD}/caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/caddy/conf/index.html:/home/index.html

  fava:
    container_name: fava
    build:
      network: host
      context: fava
    image: fava
    restart: unless-stopped
    command: fava --host=0.0.0.0 --port=5000 /app/accounts/main.bean
    environment:
      - TZ
    ports:
      - ${FAVA_PORT:-5000}:5000
    volumes:
      - ${PWD}/fava/data/accounts:/app/accounts

  books:
    container_name: books
    image: carderne/calibre-flask:latest
    restart: unless-stopped
    environment:
      - TZ
      - BOOKS_PREFIX=/books
    volumes:
      - ${PWD}/books/data:/app/app/data
    ports:
      - ${BOOKS_PORT:-5001}:8000

  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:0.6.21
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ${PWD}/calibre-web/conf:/config
      - ${PWD}/books/data:/books
    ports:
      - ${CALIBRE_PORT:-5002}:8083
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:amd64-4.0.5-r0-ls222
    restart: unless-stopped
    volumes:
      - ${PWD}/transmission/conf:/config
      - ${PWD}/downloads:/downloads
    ports:
      - ${TRANSMISSION_PORT:-5004}:9091
    environment:
      - TZ
      - PUID=1000
      - PGID=1000
      - USER=${TRANSMISSION_USERNAME:-admin}
      - PASS=${TRANSMISSION_PASSWORD:-admin}
    dns:
      - 9.9.9.9

  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.44
    restart: unless-stopped
    volumes:
      - ${PWD}/adguard/data:/opt/adguardhome/work
      - ${PWD}/adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${ADGUARD_PORT:-5005}:80
    networks:
      dockervlan:
        ipv4_address: 192.168.178.19

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.8.13
    volumes:
      - ${PWD}/jellyfin/conf:/config
      - ${PWD}/media/Movies:/media/Movies
      - ${PWD}/media/Series:/media/Series
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
      - JELLYFIN_PublishedServerUrl=http://box.local/
    restart: "unless-stopped"
    ports:
      - ${JELLYFIN_PORT:-5009}:8096

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${PWD}/homeassistant/conf:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
