api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: acme@thisprops.com 
      storage: /shared/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: ERROR
